import React, { useEffect, useMemo, useState } from 'react';
import { useLocation, useOutletContext } from 'react-router-dom';
import { FaBoxOpen, FaChevronDown, FaChevronUp, FaFileExcel, FaFilePdf, FaPlus, FaSearch, FaTruck, FaUndo } from 'react-icons/fa';
import toast from 'react-hot-toast';
import { API_BASE, anularMovimientoMaterialPOA, descargarConsolidadoRequerimientosExcelPOA, getConsolidadoRequerimientosPOA, getOrdenesCompraPOA, getProgramasPOA } from '../../../apis/poa.api';
import FullscreenPDFViewer from '../../../components/FullscreenPDFViewer';
import Dialog from '../components/base/Dialog';
import NuevaOrdenCompraModal from '../components/NuevaOrdenCompraModal';
import RegistrarRecepcionModal from '../components/RegistrarRecepcionModal';
import RegistrarEntregaModal from '../components/RegistrarEntregaModal';

const STATUS = { emitida: 'Emitida', recibiendo: 'Recibiendo', recibida: 'Recibida', cancelada: 'Cancelada' };

export default function ConsolidadoRequerimientosPage() {
  const { poaPermissions = {} } = useOutletContext() || {}; const location = useLocation(); const canEdit = !!poaPermissions.canEdit;
  const [filtros, setFiltros] = useState({ gestion: new Date().getFullYear(), programa: '', partida: '', item: '', mes_requerimiento: '' });
  const [programas, setProgramas] = useState([]), [datos, setDatos] = useState({ items: [] }), [ordenes, setOrdenes] = useState([]), [tab, setTab] = useState(() => location.state?.materialTab || 'req'), [abierto, setAbierto] = useState(null), [orden, setOrden] = useState(null), [recepcion, setRecepcion] = useState(null), [entrega, setEntrega] = useState(null), [anular, setAnular] = useState(null), [motivo, setMotivo] = useState(''), [pdfAbierto, setPdfAbierto] = useState(false);
  const cargar = async () => { try { const [r, o] = await Promise.all([getConsolidadoRequerimientosPOA(filtros), getOrdenesCompraPOA({ gestion: filtros.gestion })]); setDatos(r.data); setOrdenes(Array.isArray(o.data) ? o.data : o.data?.results || []); } catch { toast.error('No se pudieron cargar los materiales.'); } };
  useEffect(() => { getProgramasPOA({ activo: true }).then((r) => setProgramas(Array.isArray(r.data) ? r.data : r.data?.results || [])).catch(() => {}); cargar(); }, []);
  useEffect(() => { if (location.state?.materialTab) setTab(location.state.materialTab); }, [location.state?.materialTab]);
  const stock = useMemo(() => ordenes.flatMap((o) => (o.recepciones || []).filter((r) => !r.anulada).flatMap((r) => (r.detalles || []).map((d) => ({ o, r, d, linea: o.detalles.find((x) => +x.id === +d.detalle_orden) })).filter((x) => +x.d.saldo_entrega > 0))), [ordenes]);
  const exportarExcel = async () => { try { const r = await descargarConsolidadoRequerimientosExcelPOA(filtros); const url = URL.createObjectURL(r.data); const a = document.createElement('a'); a.href = url; a.download = `materiales_poa_${filtros.gestion}.xlsx`; a.click(); URL.revokeObjectURL(url); } catch { toast.error('No se pudo generar el archivo Excel.'); } };
  const consolidadoPdfUrl = `${API_BASE}/api/poa/consolidado-requerimientos/?${new URLSearchParams({ ...filtros, formato: 'pdf' }).toString()}`;
  const confirmar = async () => { if (!motivo.trim()) return toast.error('Indique el motivo.'); try { await anularMovimientoMaterialPOA(anular.tipo, anular.id, motivo); toast.success('Movimiento anulado; el historial se conserva.'); setAnular(null); setMotivo(''); cargar(); } catch (e) { toast.error(e?.response?.data?.detail || 'No se pudo anular.'); } };
  const cambiar = (key, value) => setFiltros((f) => ({ ...f, [key]: value }));
  const anularBtn = (tipo, id, label) => canEdit && <button className="text-xs font-bold text-red-600 hover:underline" onClick={() => setAnular({ tipo, id, label })}><FaUndo className="mr-1 inline" />Anular</button>;
  return <section className="mx-auto w-full max-w-[1500px]"><div className="rounded-2xl border border-blue-200 bg-white/80 p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900/70"><div className="flex justify-between gap-3"><div><h2 className="text-2xl font-extrabold text-blue-900 dark:text-white">Materiales POA</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Requerimientos, compras, recepciones y entregas de su carrera.</p></div>{!canEdit && <span className="text-xs font-bold text-slate-500">Modo consulta</span>}</div><div className="mt-4 flex gap-4 border-b dark:border-slate-700">{[['req','Requerimientos'],['ordenes','Órdenes y recepciones'],['entregas','Entregas']].map(([id,n]) => <button key={id} onClick={() => setTab(id)} className={`border-b-2 px-2 py-2 text-sm font-bold ${tab === id ? 'border-blue-600 text-blue-700' : 'border-transparent text-slate-500'}`}>{n}</button>)}</div></div>
    {tab === 'req' && <><div className="mt-4 rounded-xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label>Gestión<input className="poa-input mt-1 w-full" type="number" value={filtros.gestion} onChange={(e) => cambiar('gestion', e.target.value)} /></label><label>Programa<select className="poa-input mt-1 w-full" value={filtros.programa} onChange={(e) => cambiar('programa', e.target.value)}><option value="">Todos</option>{programas.map((p) => <option key={p.id} value={p.nombre}>{p.nombre}</option>)}</select></label><label>Partida<input className="poa-input mt-1 w-full" value={filtros.partida} onChange={(e) => cambiar('partida', e.target.value)} /></label><label>Ítem<input className="poa-input mt-1 w-full" value={filtros.item} onChange={(e) => cambiar('item', e.target.value)} /></label><label>Mes<input className="poa-input mt-1 w-full" value={filtros.mes_requerimiento} onChange={(e) => cambiar('mes_requerimiento', e.target.value)} /></label></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-primary rounded px-3 py-2" onClick={cargar}><FaSearch className="mr-1 inline" />Actualizar</button><button className="btn-success rounded px-3 py-2" onClick={exportarExcel}><FaFileExcel className="mr-1 inline" />Excel</button><button className="btn-secondary rounded px-3 py-2" onClick={() => setPdfAbierto(true)}><FaFilePdf className="mr-1 inline" />Ver PDF</button>{canEdit && <button disabled={!datos.items?.length} className="btn-primary rounded px-3 py-2" onClick={() => setOrden(true)}><FaPlus className="mr-1 inline" />Registrar compra</button>}</div></div><div className="mt-4 overflow-x-auto rounded-xl border bg-white dark:border-slate-700 dark:bg-slate-900"><table className="w-full text-sm"><thead><tr className="bg-blue-50 text-left dark:bg-slate-800"><th className="p-3">Partida</th><th>Ítem</th><th>Unidad</th><th>Cantidad</th><th>Costo</th><th /></tr></thead><tbody>{datos.items?.map((i,n) => <React.Fragment key={`${i.partida}-${i.item}-${n}`}><tr className="border-t dark:border-slate-700"><td className="p-3">{i.partida}</td><td><b>{i.item}</b></td><td>{i.unidad_medida}</td><td>{i.cantidad_total}</td><td>{Number(i.monto_estimado_total).toFixed(2)}</td><td><button onClick={() => setAbierto(abierto === n ? null : n)}>{abierto === n ? <FaChevronUp/> : <FaChevronDown/>}</button></td></tr>{abierto === n && <tr><td colSpan="6" className="bg-slate-50 p-3 text-xs dark:bg-slate-800">{i.origenes.map((x) => <p key={x.detalle_id}>{x.programa} · {x.actividad_codigo}: {x.actividad_nombre} — {x.cantidad}</p>)}</td></tr>}</React.Fragment>)}</tbody></table></div></>}
    {tab === 'ordenes' && <div className="mt-4 space-y-3">{ordenes.map((o) => <article key={o.id} className="rounded-xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><div className="flex justify-between gap-3"><div><b>Orden {o.numero}</b><p className="text-sm text-slate-500">{o.proveedor} · {o.fecha}</p></div><div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{STATUS[o.estado] || o.estado}</span>{o.estado !== 'cancelada' && anularBtn('orden',o.id,`la orden ${o.numero}`)}</div></div><table className="mt-3 w-full text-sm"><thead><tr className="text-left text-slate-500"><th>Ítem</th><th>Comprado</th><th>Recibido</th><th>Entregado</th><th>Saldo</th></tr></thead><tbody>{o.detalles.map((d) => <tr key={d.id} className="border-t dark:border-slate-700"><td className="py-2">{d.item}</td><td>{d.cantidad_comprada}</td><td>{d.cantidad_recibida}</td><td>{d.cantidad_entregada}</td><td>{d.saldo_recepcion}</td></tr>)}</tbody></table>{canEdit && o.estado !== 'cancelada' && o.detalles.some((d) => +d.saldo_recepcion > 0) && <button className="btn-primary mt-3 rounded px-3 py-2 text-sm" onClick={() => setRecepcion(o)}><FaTruck className="mr-1 inline"/>Registrar recepción</button>}{(o.recepciones || []).map((r) => <div key={r.id} className="mt-2 flex justify-between rounded bg-slate-50 p-2 text-xs dark:bg-slate-800"><span>{r.fecha} · {r.recibido_por || 'Sin responsable'} {r.anulada && '(Anulada)'}</span>{!r.anulada && anularBtn('recepcion',r.id,'esta recepción')}</div>)}</article>)}{!ordenes.length && <p className="rounded-xl border border-dashed p-8 text-center text-slate-500">No hay órdenes en esta gestión.</p>}</div>}
    {tab === 'entregas' && <div className="mt-4 space-y-3"><p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900 dark:bg-slate-800 dark:text-amber-100">El receptor se guarda como dato del acta, sin crearle usuario POA.</p>{stock.map(({o,r,d,linea}) => <article key={d.id} className="rounded-xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><div className="flex justify-between gap-3"><div><b>{linea?.item}</b><p className="text-sm text-slate-500">Orden {o.numero} · recepción {r.fecha} · disponible: {d.saldo_entrega}</p></div>{canEdit && <button className="btn-primary rounded px-3 py-2 text-sm" onClick={() => setEntrega({detalleRecepcion:d,detalleOrden:linea})}><FaBoxOpen className="mr-1 inline"/>Entregar</button>}</div>{d.entregas?.map((e) => <div key={e.id} className="mt-2 flex justify-between rounded bg-slate-50 p-2 text-xs dark:bg-slate-800"><span>{e.cantidad_entregada} a {e.actividad_codigo} · {e.nombre_receptor}</span>{!e.anulada && anularBtn('entrega',e.id,'esta entrega')}</div>)}</article>)}{!stock.length && <p className="rounded-xl border border-dashed p-8 text-center text-slate-500">No hay material recibido pendiente de entrega.</p>}</div>}
    {orden && <NuevaOrdenCompraModal gestion={filtros.gestion} items={datos.items} onClose={() => setOrden(null)} onCreated={cargar}/>} {recepcion && <RegistrarRecepcionModal orden={recepcion} onClose={() => setRecepcion(null)} onSaved={cargar}/>} {entrega && <RegistrarEntregaModal {...entrega} onClose={() => setEntrega(null)} onSaved={cargar}/>}<Dialog open={!!anular} type="danger" title="Anular movimiento" message={`Se conservará el historial de ${anular?.label || 'este movimiento'}.`} confirmText="Anular" onConfirm={confirmar} onClose={() => {setAnular(null);setMotivo('');}}><textarea className="poa-input w-full" placeholder="Motivo obligatorio" value={motivo} onChange={(e) => setMotivo(e.target.value)}/></Dialog>
    <FullscreenPDFViewer isOpen={pdfAbierto} onClose={() => setPdfAbierto(false)} pdfUrl={consolidadoPdfUrl} downloadFileName={`solicitud_compra_poa_${filtros.gestion}.pdf`} title={`Solicitud de compra POA - Gestión ${filtros.gestion}`} />
  </section>;
}
