import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { FaArrowRight, FaCalendarAlt, FaChartLine, FaClipboardCheck, FaExclamationTriangle, FaFileAlt, FaImage, FaMoneyBillWave } from 'react-icons/fa';
import { getBandejaSeguimientoPOA, getTableroPOA } from '../../../apis/poa.api';

const money = (v) => `Bs. ${Number(v || 0).toLocaleString('es-BO', { minimumFractionDigits: 2 })}`;
const estados = { elaboracion: 'En elaboración', revision: 'En revisión', observado: 'Observados', aprobado: 'Aprobados', ejecucion: 'En ejecución' };
const Kpi = ({ label, value, Icon, tone = 'text-[#365d7d]' }) => <div className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-wide text-slate-600 dark:text-slate-300">{label}</span><Icon className={tone} /></div><b className={`mt-1 block text-2xl ${tone}`}>{value}</b></div>;

export default function POAHomePage() {
  const navigate = useNavigate(); const location = useLocation();
  const [modo, setModo] = useState(() => location.state?.modo || 'ejecucion'); const [data, setData] = useState(null); const [tablero, setTablero] = useState(null); const [error, setError] = useState('');
  useEffect(() => { if (location.state?.modo) setModo(location.state.modo); }, [location.state?.modo]);
  useEffect(() => { const gestion = new Date().getFullYear(); setData(null); setError(''); Promise.all([getBandejaSeguimientoPOA({ gestion, modo }), getTableroPOA({ gestion })]).then(([b, t]) => { setData(b.data); setTablero(t.data); }).catch(() => setError('No se pudo cargar el tablero de trabajo.')); }, [modo]);
  if (error) return <div className="mx-auto mt-6 w-full max-w-[1500px] rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>;
  if (!data || !tablero) return <div className="mx-auto mt-6 w-full max-w-[1500px] text-sm text-slate-700 dark:text-slate-200">Cargando tablero de trabajo…</div>;
  const r = data.resumen || {}; const e = tablero.estados_documento || {}; const agenda = tablero.agenda_mensual || {}; const p = tablero.presupuesto || {};
  const fisico = Number(r.avance_fisico || 0); const financiero = Number(p.planificado) ? Math.round(Number(p.comprometido || 0) / Number(p.planificado) * 100) : 0;
  const kpis = modo === 'ejecucion' ? [['Programas activos', r.documentos, FaFileAlt], ['Actividades activas', r.actividades, FaClipboardCheck], ['Avance físico', `${fisico}%`, FaChartLine, 'text-[#467565]'], ['Sin evidencia', Math.max(0, r.actividades - r.con_evidencia), FaImage, 'text-[#9a7040]']] : [['En elaboración', e.elaboracion || 0, FaFileAlt], ['En revisión', e.revision || 0, FaClipboardCheck], ['Observados', e.observado || 0, FaExclamationTriangle, 'text-[#9a7040]'], ['Aprobados', e.aprobado || 0, FaChartLine, 'text-[#467565]']];
  const abrirAlerta = (a) => { if (a.accion === 'ver_materiales') navigate('/poa/materiales'); else if (a.referencia?.documento_id) navigate(`/poa/seguimiento/programa/${a.referencia.documento_id}`, { state: { modo: 'ejecucion' } }); };
  return <section className="mx-auto w-full max-w-[1500px] pb-8 text-slate-800 dark:text-slate-100">
    <header className="rounded-2xl border border-slate-300 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#365d7d] dark:text-slate-300">Gestión POA · {data.gestion}</p><div className="mt-1 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-extrabold text-slate-900 dark:text-white">Bandeja de trabajo</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Controle la preparación documental, la ejecución de actividades y los materiales de su carrera.</p></div><div className="text-right"><p className="text-[10px] font-bold uppercase text-slate-600 dark:text-slate-300">Presupuesto comprometido</p><b>{money(p.comprometido)} <span className="text-xs text-slate-600 dark:text-slate-300">/ {money(p.planificado)}</span></b></div></div><nav className="mt-4 flex gap-5 border-b"><button onClick={() => setModo('ejecucion')} className={`border-b-2 pb-2 text-sm font-bold ${modo === 'ejecucion' ? 'border-[#365d7d] text-[#294b67] dark:text-white' : 'border-transparent text-slate-600 dark:text-slate-300'}`}>Ejecución</button><button onClick={() => setModo('planificado')} className={`border-b-2 pb-2 text-sm font-bold ${modo === 'planificado' ? 'border-[#365d7d] text-[#294b67] dark:text-white' : 'border-transparent text-slate-600 dark:text-slate-300'}`}>Planificación</button></nav></header>
    <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{kpis.map(([l, v, I, t]) => <Kpi key={l} label={l} value={v} Icon={I} tone={t} />)}</div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,.55fr)]"><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex justify-between"><div><h3 className="font-bold text-slate-900 dark:text-white">{modo === 'ejecucion' ? 'Programas en ejecución' : 'Documentos en planificación'}</h3><p className="text-xs text-slate-600 dark:text-slate-300">Abra un programa para acceder a sus objetivos, actividades y evidencias.</p></div><b className="text-xs text-slate-600 dark:text-slate-300">{data.programas.length} documentos</b></div><div className="mt-3 space-y-2">{data.programas.map((x) => <button key={x.id} onClick={() => navigate(`/poa/seguimiento/programa/${x.id}`, { state: { modo } })} className="w-full rounded-xl border border-slate-200 p-3 text-left transition hover:border-[#7891a8] hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800"><div className="flex justify-between gap-3"><div><b className="text-slate-800 dark:text-white">{x.programa}</b><p className="mt-1 text-xs text-slate-600 dark:text-slate-300">{modo === 'planificado' ? estados[x.estado_documento] : `${x.en_ejecucion} en ejecución · ${x.completadas}/${x.total_actividades} completadas`}</p></div><FaArrowRight className="mt-2 text-[#365d7d]" /></div>{modo === 'ejecucion' && <div className="mt-2 h-1.5 rounded bg-slate-200"><div className="h-full rounded bg-[#467565]" style={{ width: `${x.avance_porcentaje}%` }} /></div>}</button>)}{!data.programas.length && <p className="rounded-xl border border-dashed p-6 text-center text-sm text-slate-600 dark:text-slate-300">No hay documentos para esta vista.</p>}</div></section>
      <aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 className="font-bold text-slate-900 dark:text-white"><FaCalendarAlt className="mr-2 inline text-[#365d7d]" />Agenda de {agenda.mes || 'este mes'}</h3><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><p className="rounded bg-slate-100 p-2 dark:bg-slate-800">Programadas <b className="block">{agenda.programadas || 0}</b></p><p className="rounded bg-slate-100 p-2 dark:bg-slate-800">En curso <b className="block">{agenda.en_ejecucion || 0}</b></p><p className="rounded bg-slate-100 p-2 dark:bg-slate-800">Completadas <b className="block">{agenda.completadas || 0}</b></p><p className="rounded bg-slate-100 p-2 dark:bg-slate-800">Retrasadas <b className="block">{agenda.retrasadas || 0}</b></p></div></section><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 className="font-bold text-slate-900 dark:text-white"><FaExclamationTriangle className="mr-2 inline text-[#9a7040]" />Trabajo prioritario</h3><div className="mt-2 space-y-2">{tablero.alertas?.length ? tablero.alertas.map((a, i) => <button key={i} onClick={() => abrirAlerta(a)} className="w-full rounded-lg bg-slate-100 p-2 text-left text-xs text-slate-700 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-200">{a.mensaje}</button>) : <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-200">No hay acciones pendientes.</p>}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-4 text-sm shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 className="font-bold text-slate-900 dark:text-white"><FaMoneyBillWave className="mr-2 inline text-[#365d7d]" />Ejecución presupuestaria</h3><p className="mt-2 text-slate-600 dark:text-slate-300">Comprometido: <b>{financiero}%</b></p><div className="mt-1 h-2 rounded bg-slate-200"><div className="h-full rounded bg-[#365d7d]" style={{ width: `${financiero}%` }} /></div><p className="mt-3 text-xs text-slate-600 dark:text-slate-300">Recibido: <b>{money(p.recibido)}</b><br />Entregado: <b>{money(p.entregado)}</b></p></section></aside></div>
  </section>;
}
