# Generated by Django 5.2.7 on 2025-11-03 05:41
# FIX: 0001_initial already creates PerfilUsuario, so this migration
# only updates Django's migration state without touching the DB.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
