# Generated by Django 5.2.7 on 2025-11-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0003_fondotiempo_aprobado_por_fondotiempo_archivado_and_more'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
