# Generated by Django 5.2.7 on 2025-11-18 06:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0004_alter_fondotiempo_unique_together_and_more'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
