# Generated by Django 5.2.7 on 2025-11-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0005_calendarioacademico_fondotiempo_calendario_academico'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
