# Generated by Django 5.2.7 on 2025-11-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0009_alter_informefondo_archivo_url_and_more'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
