# Generated by Django 5.2.7 on 2025-11-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0010_remove_fondotiempo_total_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
