# Generated by Django 5.2.7 on 2025-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0012_docente_fecha_modificacion'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
