# Generated by Django 5.2.7 on 2025-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0013_fondotiempo_fecha_finalizacion_and_more'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
