# Generated by Django 5.2.7 on 2025-11-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0014_informefondo_logros'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
