# Generated by Django 5.2.7 on 2026-02-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0015_informefondo_dificultades'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
