# Generated by Django 5.2.7 on 2026-02-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0016_perfilusuario_foto_perfil'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
