# Generated by Django 5.2.7 on 2026-02-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0017_alter_fondotiempo_unique_together_and_more'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
