# Generated by Django 5.2.7 on 2026-02-13 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0019_remove_informefondo_archivo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
