# Generated by Django 6.0.2 on 2026-02-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0021_alter_actividad_evidencias'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
