# Generated by Django 5.2.7 on 2026-02-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0022_alter_actividad_evidencias'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
