# Generated by Django 6.0.2 on 2026-02-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0023_docente_dias_vacacion_docente_horas_feriados_gestion'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
