# Generated by Django 6.0.2 on 2026-02-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0024_perfilusuario_debe_cambiar_password'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
