# Generated by Django 6.0.2 on 2026-02-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0025_materia'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
