# Generated by Django 6.0.2 on 2026-02-20 18:19

import fondos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0026_alter_materia_sigla'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
