# Generated by Django 6.0.2 on 2026-02-20 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0027_actividad_archivo_evidencia'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
