# Generated by Django 5.2.7 on 2026-03-19 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0029_perfilusuario_foto_cifrada'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
