# Generated by Django 5.2.7 on 2026-04-13 12:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0057_docente_carrera_multicarrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultadCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cargahoraria',
            name='aula',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cargahoraria',
            name='dia_semana',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado')], default='lunes', max_length=10),
        ),
        migrations.AlterField(
            model_name='cargahoraria',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargahoraria',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargahoraria',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Materia del plan de estudios asignada al docente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_horarias', to='fondos.materia'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='facultad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='docente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el docente está activo en la institución'),
        ),
        migrations.AlterField(
            model_name='fondotiempo',
            name='semanas_año',
            field=models.DecimalField(decimal_places=1, default=Decimal('45.8'), help_text='Número de semanas efectivas del año para cálculo de horas anuales', max_digits=4),
        ),
        migrations.AlterField(
            model_name='historicalcarrera',
            name='facultad',
            field=models.CharField(max_length=200),
        ),
    ]
