# Generated by Django 5.2.7 on 2026-04-14 04:52

from django.conf import settings
from django.db import migrations, models


def migrate_admin_to_iiisyp(apps, schema_editor):
    """Convertir todos los roles 'admin' existentes a 'iiisyp'."""
    AsignacionCarrera = apps.get_model('fondos', 'AsignacionCarrera')
    PerfilUsuario = apps.get_model('fondos', 'PerfilUsuario')

    AsignacionCarrera.objects.filter(rol='admin').update(rol='iiisyp')
    PerfilUsuario.objects.filter(rol='admin').update(rol='iiisyp')


def reverse_iiisyp_to_admin(apps, schema_editor):
    """Revertir 'iiisyp' a 'admin' (rollback)."""
    AsignacionCarrera = apps.get_model('fondos', 'AsignacionCarrera')
    PerfilUsuario = apps.get_model('fondos', 'PerfilUsuario')

    AsignacionCarrera.objects.filter(rol='iiisyp').update(rol='admin')
    PerfilUsuario.objects.filter(rol='iiisyp').update(rol='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0058_facultadcatalogo_alter_cargahoraria_aula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='perfilusuario',
            name='unico_admin_por_carrera',
        ),
        migrations.RunPython(
            migrate_admin_to_iiisyp,
            reverse_code=reverse_iiisyp_to_admin,
        ),
        migrations.AlterField(
            model_name='asignacioncarrera',
            name='rol',
            field=models.CharField(choices=[('iiisyp', 'Instituto I.I.S. y P.'), ('director', 'Director de Carrera'), ('jefe_estudios', 'Jefe de Estudios'), ('docente', 'Docente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('iiisyp', 'Instituto I.I.S. y P.'), ('director', 'Director de Carrera'), ('jefe_estudios', 'Jefe de Estudios'), ('docente', 'Docente')], default='docente', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('rol', 'iiisyp')), fields=('carrera', 'rol'), name='unico_iiisyp_por_carrera'),
        ),
    ]
