# Generated by Django 5.2.7 on 2026-07-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0064_calendarioacademico_fechas_complementarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentecarrera',
            name='condicion',
            field=models.CharField(choices=[('titular', 'Titular'), ('invitado', 'Invitado')], default='titular', max_length=10),
        ),
        migrations.AlterField(
            model_name='docentecarrera',
            name='dedicacion',
            field=models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('horario_16', 'Horario 16hrs/mes'), ('horario_24', 'Horario 24hrs/mes'), ('horario_40', 'Horario 40hrs/mes'), ('horario_48', 'Horario 48hrs/mes'), ('dedicacion_exclusiva', 'Dedicacion Exclusiva')], max_length=20),
        ),
    ]
