# Generated by Django 5.2.7 on 2026-07-25 01:46

from django.db import migrations, models


OLD_TO_NEW_CATEGORY = {
    'docente': 'academica',
    'asesorias': 'academica',
    'investigacion': 'investigacion',
    'extension': 'extension_universitaria',
    'administrativo': 'gestion',
    'tribunales': 'academica_administrativa',
    'vida_universitaria': 'social_cultural_deportiva',
}

REQUIRED_CATEGORIES = [
    'academica',
    'investigacion',
    'extension_universitaria',
    'interaccion_social',
    'gestion',
    'academica_administrativa',
    'social_cultural_deportiva',
]


def migrate_distribution_categories(apps, schema_editor):
    FondoTiempo = apps.get_model('fondos', 'FondoTiempo')
    CategoriaFuncion = apps.get_model('fondos', 'CategoriaFuncion')
    Actividad = apps.get_model('fondos', 'Actividad')
    Proyecto = apps.get_model('fondos', 'Proyecto')
    CargaHoraria = apps.get_model('fondos', 'CargaHoraria')

    for old_value, new_value in OLD_TO_NEW_CATEGORY.items():
        CargaHoraria.objects.filter(categoria=old_value).update(categoria=new_value)

    for fondo in FondoTiempo.objects.all().iterator():
        categorias = list(CategoriaFuncion.objects.filter(fondo_tiempo=fondo).order_by('id'))

        for categoria in categorias:
            target_tipo = OLD_TO_NEW_CATEGORY.get(categoria.tipo, categoria.tipo)
            if target_tipo == categoria.tipo:
                continue

            target = CategoriaFuncion.objects.filter(
                fondo_tiempo=fondo,
                tipo=target_tipo,
            ).exclude(pk=categoria.pk).first()

            if target:
                Actividad.objects.filter(categoria=categoria).update(categoria=target)
                Proyecto.objects.filter(categoria=categoria).update(categoria=target)
                target.total_horas = (target.total_horas or 0) + (categoria.total_horas or 0)
                target.save(update_fields=['total_horas'])
                categoria.delete()
            else:
                categoria.tipo = target_tipo
                categoria.save(update_fields=['tipo'])

        for tipo in REQUIRED_CATEGORIES:
            CategoriaFuncion.objects.get_or_create(fondo_tiempo=fondo, tipo=tipo)


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0065_docentecarrera_condicion_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_distribution_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cargahoraria',
            name='categoria',
            field=models.CharField(choices=[('academica', 'Académica'), ('investigacion', 'Investigación'), ('extension_universitaria', 'Extensión universitaria'), ('interaccion_social', 'Interacción social'), ('gestion', 'Gestión'), ('academica_administrativa', 'Académica-administrativa'), ('social_cultural_deportiva', 'Social, cultural, deportiva y Otros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='categoriafuncion',
            name='tipo',
            field=models.CharField(choices=[('academica', 'Académica'), ('investigacion', 'Investigación'), ('extension_universitaria', 'Extensión universitaria'), ('interaccion_social', 'Interacción social'), ('gestion', 'Gestión'), ('academica_administrativa', 'Académica-administrativa'), ('social_cultural_deportiva', 'Social, cultural, deportiva y Otros')], max_length=30),
        ),
    ]
