# Generated by Django 5.2.7 on 2026-07-28 06:13

import django.db.models.deletion
from django.db import migrations, models


def asignar_carrera_a_calendarios_existentes(apps, schema_editor):
    CalendarioAcademico = apps.get_model('fondos', 'CalendarioAcademico')
    Carrera = apps.get_model('fondos', 'Carrera')
    carrera = Carrera.objects.order_by('id').first()
    if carrera:
        CalendarioAcademico.objects.filter(carrera__isnull=True).update(carrera=carrera)


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0066_alter_cargahoraria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarioacademico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calendarioacademico',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Carrera a la que pertenece este calendario academico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendarios_academicos', to='fondos.carrera'),
        ),
        migrations.RunPython(asignar_carrera_a_calendarios_existentes, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='calendarioacademico',
            unique_together={('carrera', 'gestion', 'periodo')},
        ),
    ]
