# Generated by Codex on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0067_alter_calendarioacademico_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarioacademico',
            name='carrera',
            field=models.ForeignKey(
                help_text='Carrera a la que pertenece este calendario academico',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='calendarios_academicos',
                to='fondos.carrera',
            ),
        ),
    ]
