# Generated by Django 5.2.7 on 2026-08-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0069_cargahoraria_titulo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeobservacion',
            name='leido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
