# Generated by Django 5.2.7 on 2026-09-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0072_seed_facultades_oficiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='subactividad_academica',
            field=models.CharField(blank=True, choices=[('preparacion_temas', 'Preparación de temas'), ('clases_aula', 'Clases en aula'), ('elaboracion_trabajos_practicos', 'Elaboración de Trabajos Prácticos'), ('revision_calificacion_trabajos_practicos', 'Revisión y Calificación de Trabajos Prácticos'), ('elaboracion_examenes', 'Elaboración de Exámenes'), ('revision_calificacion_examenes', 'Revisión y Calificación de Exámenes'), ('practica_laboratorios', 'Práctica de Laboratorios'), ('practicas_campo', 'Prácticas de Campo'), ('produccion_docente_textos_guias', 'Producción docente (textos guías)'), ('consultas_reclamos_calificaciones', 'Consultas y Reclamos de Calificaciones'), ('elaboracion_planillas_introduccion_notas', 'Elaboración de planillas e Introducción de notas'), ('planificacion_gestion_practica_extra_aula', 'Planificación y gestión de práctica extra aula'), ('ejecucion_practica_extra_aula', 'Ejecución de práctica extra aula'), ('informe_descargo_viaje_practicas_extra_aula', 'Informe de descargo de viaje en prácticas extra aula'), ('cursos_verano', 'Cursos de verano')], help_text='Sub-actividad pedagógica reglamentaria para la categoría Académica', max_length=60),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='evidencia',
            field=models.FileField(blank=True, help_text='Evidencia digital del informe final (PDF/Imagen)', null=True, upload_to='evidencias/'),
        ),
        migrations.CreateModel(
            name='InformeAsignaturaEjecutada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=200)),
                ('inscritos', models.PositiveIntegerField(default=0)),
                ('aprobados', models.PositiveIntegerField(default=0)),
                ('reprobados', models.PositiveIntegerField(default=0)),
                ('habilitados', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fondo_tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_ejecutadas', to='fondos.fondotiempo')),
            ],
            options={
                'verbose_name': 'Asignatura Ejecutada en Informe',
                'verbose_name_plural': 'Asignaturas Ejecutadas en Informes',
                'ordering': ['nombre_materia'],
            },
        ),
    ]
