# Generated by Django 5.2.7 on 2026-09-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0074_recalcular_horas_efectivas_doble_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentecarrera',
            name='dedicacion',
            field=models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('horario_16', 'Horario 16hrs/sem'), ('horario_24', 'Horario 24hrs/sem'), ('horario_40', 'Horario 40hrs/sem'), ('horario_48', 'Horario 48hrs/sem'), ('dedicacion_exclusiva', 'Dedicacion Exclusiva')], max_length=20),
        ),
    ]
