# Generated by Django 5.2.7 on 2026-09-12 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0084_balance_academic_subactivities_by_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['categoria', 'orden', 'id'], 'verbose_name': 'Actividad (OBSOLETO - usar CargaHoraria)', 'verbose_name_plural': 'Actividades (OBSOLETO - usar CargaHoraria)'},
        ),
        migrations.AddConstraint(
            model_name='cargahoraria',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categoria', 'academica'), ('materia__isnull', False)), models.Q(('categoria', 'academica'), _negated=True), _connector='OR'), name='cargahoraria_materia_obligatoria_si_academica'),
        ),
        migrations.AddConstraint(
            model_name='cargahoraria',
            constraint=models.UniqueConstraint(condition=models.Q(('categoria', 'academica')), fields=('docente', 'calendario', 'categoria', 'tipo_actividad', 'materia'), name='cargahoraria_unique_tipo_academica_por_materia'),
        ),
        migrations.AddConstraint(
            model_name='cargahoraria',
            constraint=models.UniqueConstraint(condition=models.Q(('categoria', 'academica'), _negated=True), fields=('docente', 'calendario', 'categoria', 'tipo_actividad'), name='cargahoraria_unique_tipo_no_academica'),
        ),
    ]
