# Generated by Django 5.2.7 on 2026-09-13 16:01

import django.core.validators
import django.db.models.deletion
import fondos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0085_cargahoraria_constraints_integridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeobservacion',
            name='es_interno',
            field=models.BooleanField(default=False, help_text='Si es True, el mensaje es una nota interna entre Director y Jefe de Estudios: no se muestra al docente dueño del fondo, solo a Director, Jefe de Estudios y administradores.'),
        ),
        migrations.CreateModel(
            name='EvidenciaCargaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='PDF, imagen (JPG/PNG) o documento Word (DOCX) que respalda el cumplimiento de la actividad.', upload_to=fondos.models.evidencia_carga_horaria_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx'])])),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripcion opcional del archivo adjunto.', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('carga_horaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_evidencia', to='fondos.cargahoraria')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_carga_horaria_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de Carga Horaria',
                'verbose_name_plural': 'Evidencias de Carga Horaria',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
