# Generated by Django 5.2.7 on 2026-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0086_evidencia_carga_horaria_y_mensaje_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefondo',
            name='conclusiones_generales',
            field=models.TextField(blank=True, default='', help_text='Resumen final del informe y recomendaciones.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='seccion_academica',
            field=models.TextField(blank=True, default='', help_text='Cumplimiento de objetivos, resultados por materia (inscritos/aprobados/reprobados), metodologia de evaluacion.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='seccion_academica_administrativa',
            field=models.TextField(blank=True, default='', help_text='Actividades de gestion, POA, comisiones.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='seccion_asesorias_tutorias',
            field=models.TextField(blank=True, default='', help_text='Tribunales de graduacion, tutorias de proyectos.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='seccion_extension_interaccion',
            field=models.TextField(blank=True, default='', help_text='Extension universitaria e interaccion social: ferias, consultorias, cursos de actualizacion.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='seccion_investigacion',
            field=models.TextField(blank=True, default='', help_text='Proyectos de investigacion realizados, colaboraciones, resultados concretos.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='seccion_social_cultural_deportiva',
            field=models.TextField(blank=True, default='', help_text='Participacion en eventos universitarios sociales, culturales y deportivos.'),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='actividades_realizadas',
            field=models.TextField(blank=True, default='', help_text='Detalle de actividades ejecutadas (legado)'),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='dificultades',
            field=models.TextField(blank=True, help_text='Dificultades encontradas (legado)'),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='logros',
            field=models.TextField(blank=True, default='', help_text='Logros alcanzados (legado)'),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='resultados',
            field=models.TextField(blank=True, default='', help_text='Resultados obtenidos (legado)'),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='resumen_ejecutivo',
            field=models.TextField(blank=True, default='', help_text='Resumen de las actividades realizadas (legado)'),
        ),
    ]
