# Generated by Django 5.2.7 on 2026-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0087_informe_secciones_por_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefondo',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('observado', 'Observado'), ('aprobado', 'Aprobado')], default='borrador', help_text='Flujo de revision: borrador (el docente edita libremente) -> enviado (formal, ya no editable) -> observado (el Director pidio correcciones, vuelve a ser editable) -> aprobado (cierre del fondo).', max_length=10),
        ),
    ]
