# Generated by Django 5.2.7 on 2026-09-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0088_informe_estado_flujo_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefondo',
            name='cierre_html',
            field=models.TextField(blank=True, default='', help_text='Párrafos de cierre y "Atentamente,", en HTML.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='destinatario_cargo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='destinatario_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='encabezado_texto',
            field=models.TextField(blank=True, default='', help_text='Encabezado institucional (Universidad/Vicerrectorado/Facultad/Carrera), una línea por renglón.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='fecha_texto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='firma_cargo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='firma_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='firma_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='referencia_texto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='remitente_cargo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='remitente_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='saludo_intro_html',
            field=models.TextField(blank=True, default='', help_text='Saludo y párrafo introductorio, en HTML (mismo formato que las 7 secciones).'),
        ),
    ]
