# Generated by Django 5.2.7 on 2026-09-24 10:46

import fondos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0089_informe_documento_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='logo_carrera',
            field=models.ImageField(blank=True, null=True, upload_to=fondos.models.logo_carrera_upload_path),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Archivo de evidencia adjunto al informe (PDF, ZIP, etc.)', null=True, upload_to=fondos.models.informe_adjunto_upload_path),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='evidencia',
            field=models.FileField(blank=True, help_text='Evidencia digital del informe final (PDF/Imagen)', null=True, upload_to=fondos.models.informe_evidencia_upload_path),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=fondos.models.foto_perfil_upload_path),
        ),
    ]
