# Generated by Django 5.2.7 on 2026-09-26 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0090_alter_carrera_logo_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncarrera',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_carrera', to='fondos.carrera'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fondos.carrera'),
        ),
    ]
