# Generated by Django 5.2.7 on 2026-09-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0091_carrera_relaciones_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='facultad_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fondos.facultadcatalogo'),
        ),
        migrations.AddField(
            model_name='historicalcarrera',
            name='facultad_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fondos.facultadcatalogo'),
        ),
    ]
