# Generated by Django 5.2.7 on 2026-09-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0094_carrera_facultad_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentecarrera',
            name='dedicacion',
            field=models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('horario_16', 'Horario 16 hrs/mes'), ('horario_24', 'Horario 24 hrs/mes'), ('horario_40', 'Horario 40 hrs/mes'), ('horario_48', 'Horario 48 hrs/mes'), ('dedicacion_exclusiva', 'Dedicacion Exclusiva')], max_length=20),
        ),
    ]
