# Generated by Django 5.2.7 on 2026-09-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0095_dedicacion_horario_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('iiisyp', 'Instituto I.I.S. y P.'), ('director', 'Director de Carrera'), ('jefe_estudios', 'Jefe de Estudios'), ('docente', 'Docente')], default='docente', max_length=20),
        ),
    ]
