# Generated by Django 5.2.7 on 2026-09-27 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0097_superusuario_sin_rol_carrera'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='perfilusuario',
            name='unico_director_por_carrera',
        ),
        migrations.RemoveConstraint(
            model_name='perfilusuario',
            name='unico_jefe_por_carrera',
        ),
    ]
