# Generated by Django 5.2.7 on 2026-09-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0098_quitar_unicidad_cargos_perfil'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='perfilusuario',
            name='unico_iiisyp_por_carrera',
        ),
    ]
