# Generated by Django 5.2.7 on 2026-09-27 04:24

import django.core.validators
import fondos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0099_quitar_unicidad_iiisyp_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fondotiempo',
            name='unique_semestral_fondo',
        ),
        migrations.AddField(
            model_name='fondotiempo',
            name='documento_decanatura',
            field=models.FileField(blank=True, help_text='Documento de la Decanatura que respalda la aprobación del fondo de un Director', null=True, upload_to=fondos.models.documento_decanatura_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddConstraint(
            model_name='fondotiempo',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_fondo', 'semestral')), fields=('docente', 'carrera', 'gestion', 'periodo', 'asignatura'), name='unique_semestral_fondo_por_carrera'),
        ),
    ]
