# Generated by Django 5.2.7 on 2026-09-27 05:47

import django.core.validators
import fondos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0100_fondo_por_carrera_y_decanatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondotiempo',
            name='documento_decanatura_informe',
            field=models.FileField(blank=True, help_text='Documento de la Decanatura sobre el informe final del fondo de un Director', null=True, upload_to=fondos.models.documento_decanatura_informe_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
