# Generated by Django 5.2.7 on 2026-09-27 09:58

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0101_documento_decanatura_informe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAsignacionCarrera',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rol', models.CharField(choices=[('iiisyp', 'Instituto I.I.S. y P.'), ('director', 'Director de Carrera'), ('jefe_estudios', 'Jefe de Estudios'), ('docente', 'Docente')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('carrera', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fondos.carrera')),
                ('docente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fondos.docente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Asignación de Carrera',
                'verbose_name_plural': 'historical Asignaciones de Carrera',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDatosLaborales',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ci', models.CharField(db_index=True, max_length=20, verbose_name='Cédula de Identidad')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, help_text='Fecha de ingreso a la institución para cálculo de antigüedad')),
                ('dias_vacacion', models.IntegerField(default=15, help_text='Días de vacación correspondientes según antigüedad')),
                ('horas_feriados_gestion', models.IntegerField(default=128, help_text='Total de horas de feriados en la gestión académica')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Datos Laborales',
                'verbose_name_plural': 'historical Datos Laborales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, default='', max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, default='', max_length=100)),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el docente está activo en la institución')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('datos_laborales', models.ForeignKey(blank=True, db_constraint=False, help_text='Datos de empleo compartidos (CI, vacaciones, feriados, antigüedad)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fondos.datoslaborales')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario del sistema vinculado al docente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Docente',
                'verbose_name_plural': 'historical Docentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocenteCarrera',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('catedratico', 'Catedrático'), ('adjunto', 'Adjunto'), ('asistente', 'Asistente')], max_length=20)),
                ('dedicacion', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('horario_16', 'Horario 16 hrs/mes'), ('horario_24', 'Horario 24 hrs/mes'), ('horario_40', 'Horario 40 hrs/mes'), ('horario_48', 'Horario 48 hrs/mes'), ('dedicacion_exclusiva', 'Dedicacion Exclusiva')], max_length=20)),
                ('es_exento_fondo_tiempo', models.BooleanField(default=False)),
                ('condicion', models.CharField(choices=[('titular', 'Titular'), ('invitado', 'Invitado')], default='titular', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('carrera', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fondos.carrera')),
                ('docente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fondos.docente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vínculo Docente-Carrera',
                'verbose_name_plural': 'historical Vínculos Docente-Carrera',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPerfilUsuario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ci', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Cedula de Identidad')),
                ('rol', models.CharField(blank=True, choices=[('iiisyp', 'Instituto I.I.S. y P.'), ('director', 'Director de Carrera'), ('jefe_estudios', 'Jefe de Estudios'), ('docente', 'Docente')], default='docente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto_perfil', models.TextField(blank=True, max_length=100, null=True)),
                ('foto_perfil_mime', models.CharField(blank=True, default='', max_length=64)),
                ('debe_cambiar_password', models.BooleanField(default=True, help_text='Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('carrera', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fondos.carrera')),
                ('datos_laborales', models.ForeignKey(blank=True, db_constraint=False, help_text='Datos de empleo para usuarios administrativos. Si es null y tiene docente, se usan los del docente.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fondos.datoslaborales')),
                ('docente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fondos.docente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Perfil de Usuario',
                'verbose_name_plural': 'historical Perfiles de Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
