# Generated by Django 5.2.7 on 2026-09-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0102_historial_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperfilusuario',
            name='inactivo_por_ficha_pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='inactivo_por_ficha_pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
