# Generated by Django 5.2.7 on 2026-09-28 22:51

import fondos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0103_perfil_inactivo_por_ficha_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncarrera',
            name='resolucion_consejo',
            field=models.FileField(blank=True, null=True, upload_to=fondos.models.resolucion_consejo_upload_path),
        ),
        migrations.AddField(
            model_name='historicalasignacioncarrera',
            name='resolucion_consejo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
