# Generated by Django 5.2.7 on 2026-09-29 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0104_asignacion_resolucion_consejo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cargahoraria',
            name='cargahoraria_unique_tipo_academica_por_materia',
        ),
        migrations.AddField(
            model_name='materia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='cargahoraria',
            constraint=models.UniqueConstraint(condition=models.Q(('categoria', 'academica')), fields=('docente', 'calendario', 'categoria', 'tipo_actividad', 'materia', 'paralelo'), name='cargahoraria_unique_tipo_academica_por_materia_paralelo'),
        ),
    ]
