# Generated by Django 5.2.7 on 2026-09-29 10:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0105_materia_activo_y_paralelos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(error_messages={'unique': 'Ya hay un feriado registrado en esa fecha.'}, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('departamental', 'Departamental')], max_length=20)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='datoslaborales',
            name='horas_feriados_gestion',
        ),
        migrations.RemoveField(
            model_name='historicaldatoslaborales',
            name='horas_feriados_gestion',
        ),
        migrations.CreateModel(
            name='HistoricalFeriado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, error_messages={'unique': 'Ya hay un feriado registrado en esa fecha.'})),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('departamental', 'Departamental')], max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Feriado',
                'verbose_name_plural': 'historical Feriados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
