# Generated by Django 5.2.7 on 2026-09-29 17:01

from django.db import migrations, models


def presentado_jefe_a_borrador(apps, schema_editor):
    # Un fondo que el docente había presentado al Jefe vuelve a borrador: ahora lo
    # presenta Jefatura al Director.
    FondoTiempo = apps.get_model('fondos', 'FondoTiempo')
    FondoTiempo.objects.filter(estado='presentado_jefe').update(estado='borrador')


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0107_quitar_feriado_y_dias_feriados_en_calendario'),
    ]

    operations = [
        migrations.RunPython(presentado_jefe_a_borrador, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fondotiempo',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('observado', 'Con Observaciones'), ('presentado_director', 'Presentado a Director de Carrera'), ('aprobado_director', 'Aprobado por Director de Carrera'), ('en_ejecucion', 'En Ejecución'), ('informe_presentado', 'Informe Presentado'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado')], default='borrador', max_length=30),
        ),
    ]
