# Generated by Django 5.2.7 on 2026-09-30 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0108_quitar_presentado_jefe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fondotiempo',
            name='unique_semestral_fondo_por_carrera',
        ),
        migrations.RemoveField(
            model_name='calendarioacademico',
            name='semanas_efectivas',
        ),
        migrations.RemoveField(
            model_name='fondotiempo',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='fondotiempo',
            name='clases_aula_horas',
        ),
        migrations.RemoveField(
            model_name='fondotiempo',
            name='funciones_sustantivas_horas',
        ),
        migrations.RemoveField(
            model_name='fondotiempo',
            name='tipo_fondo',
        ),
        migrations.AddConstraint(
            model_name='fondotiempo',
            constraint=models.UniqueConstraint(fields=('docente', 'carrera', 'gestion', 'periodo'), name='unique_fondo_por_carrera_y_periodo'),
        ),
    ]
