# Generated by Django 5.2.7 on 2026-09-30 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def quitar_calendario_fuera_de_academica(apps, schema_editor):
    """Fuera de Académica los ítems son horas por año del fondo: sin calendario."""
    CargaHoraria = apps.get_model('fondos', 'CargaHoraria')
    CargaHoraria.objects.exclude(categoria='academica').update(calendario=None)


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0110_cargahoraria_fondo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargahoraria',
            options={'ordering': ['-fondo__gestion', 'docente', 'categoria'], 'verbose_name': 'Carga Horaria', 'verbose_name_plural': 'Cargas Horarias'},
        ),
        migrations.RemoveConstraint(
            model_name='fondotiempo',
            name='unique_fondo_por_carrera_y_periodo',
        ),
        migrations.RemoveField(
            model_name='fondotiempo',
            name='calendario_academico',
        ),
        migrations.RemoveField(
            model_name='fondotiempo',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='cargahoraria',
            name='calendario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas_horarias', to='fondos.calendarioacademico'),
        ),
        migrations.RunPython(quitar_calendario_fuera_de_academica, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cargahoraria',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calendario__isnull', False), ('categoria', 'academica')), models.Q(models.Q(('categoria', 'academica'), _negated=True), ('calendario__isnull', True)), _connector='OR'), name='cargahoraria_calendario_solo_en_academica'),
        ),
        migrations.AddConstraint(
            model_name='fondotiempo',
            constraint=models.UniqueConstraint(condition=models.Q(('archivado', False)), fields=('docente', 'gestion'), name='unique_fondo_por_docente_y_gestion'),
        ),
    ]
