# Generated by Django 5.2.7 on 2026-09-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0111_fondo_por_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondotiempo',
            name='dias_vacacion',
            field=models.IntegerField(default=0),
        ),
    ]
