# Generated by Django 5.2.7 on 2026-09-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0112_fondo_dias_vacacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriafuncion',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='categoriafuncion',
            name='total_horas',
        ),
        migrations.RemoveField(
            model_name='fondotiempo',
            name='semanas_año',
        ),
    ]
