# Generated by Django 5.2.7 on 2026-09-30 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0114_quitar_categoriafuncion_y_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cargahoraria',
            name='cargahoraria_unique_tipo_academica_por_materia_paralelo',
        ),
        migrations.RemoveConstraint(
            model_name='cargahoraria',
            name='cargahoraria_unique_tipo_no_academica_por_fondo',
        ),
        migrations.AddConstraint(
            model_name='cargahoraria',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_actividad', 'clases_aula')), fields=('fondo', 'calendario', 'materia', 'paralelo'), name='cargahoraria_unique_clase_por_calendario_materia_paralelo'),
        ),
        migrations.AddConstraint(
            model_name='cargahoraria',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_actividad', 'clases_aula'), _negated=True), fields=('fondo', 'categoria', 'tipo_actividad'), name='cargahoraria_unique_tipo_por_fondo'),
        ),
    ]
