# Generated by Django 5.2.7 on 2026-10-01 12:47

import django.core.validators
import django.db.models.deletion
import fondos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0115_clases_por_calendario_materia_paralelo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fondotiempo',
            name='programa_analitico_url',
        ),
        migrations.RemoveField(
            model_name='fondotiempo',
            name='tiene_programa_analitico',
        ),
        migrations.CreateModel(
            name='ProgramaAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=fondos.models.programa_analitico_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('fecha_subida', models.DateTimeField(auto_now=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_analiticos', to='fondos.calendarioacademico')),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_analiticos', to='fondos.fondotiempo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_analiticos', to='fondos.materia')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_analiticos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa analítico',
                'verbose_name_plural': 'Programas analíticos',
                'constraints': [models.UniqueConstraint(fields=('fondo', 'materia', 'calendario'), name='programa_analitico_unico')],
            },
        ),
    ]
