# Generated by Django 5.2.7 on 2026-10-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0116_programa_analitico_por_materia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvidenciaCargaHoraria',
        ),
    ]
