# Generated by Django 5.2.7 on 2026-10-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0117_quitar_evidencia_carga_horaria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
