# Generated by Django 5.2.7 on 2026-10-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0118_delete_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informefondo',
            name='actividades_realizadas',
        ),
        migrations.RemoveField(
            model_name='informefondo',
            name='archivo_adjunto',
        ),
        migrations.RemoveField(
            model_name='informefondo',
            name='dificultades',
        ),
        migrations.RemoveField(
            model_name='informefondo',
            name='evidencia',
        ),
        migrations.RemoveField(
            model_name='informefondo',
            name='evidencias',
        ),
        migrations.RemoveField(
            model_name='informefondo',
            name='logros',
        ),
        migrations.RemoveField(
            model_name='informefondo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='informefondo',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='informefondo',
            name='resumen_ejecutivo',
        ),
        migrations.DeleteModel(
            name='InformeAsignaturaEjecutada',
        ),
    ]
