# Generated by Django 5.2.7 on 2026-10-03 14:13

import django.core.validators
import django.db.models.deletion
import fondos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0119_quitar_campos_antiguos_informe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=fondos.models.documento_actividad_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('fecha_subida', models.DateTimeField(auto_now=True)),
                ('carga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='fondos.cargahoraria')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_actividad_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de proyecto o curso',
                'verbose_name_plural': 'Documentos de proyectos y cursos',
            },
        ),
    ]
