# Generated by Django 5.2.7 on 2026-10-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0120_documento_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondotiempo',
            name='fuera_de_plazo',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
