# Generated by Django 5.2.7 on 2026-10-03 14:23

from django.db import migrations, models


def pasar_editables_a_secciones_del_reglamento(apps, schema_editor):
    """Art. 28: los informes que el docente todavía edita (borrador u observado) pasan a las
    7 unidades: extensión e interacción -> Extensión universitaria; asesorías y tutorías ->
    Académica (Art. 13). Los presentados (enviado, aprobado) no se modifican.
    Misma regla que InformeFondo.pasar_a_secciones_del_reglamento."""
    InformeFondo = apps.get_model('fondos', 'InformeFondo')
    editables = InformeFondo.objects.filter(estado__in=['borrador', 'observado']).exclude(
        seccion_extension_interaccion='', seccion_asesorias_tutorias='',
    )
    for informe in editables:
        extension = informe.seccion_extension_interaccion.strip()
        asesorias = informe.seccion_asesorias_tutorias.strip()
        InformeFondo.objects.filter(pk=informe.pk).update(
            seccion_extension_universitaria='\n'.join(
                t for t in (informe.seccion_extension_universitaria.strip(), extension) if t
            ),
            seccion_academica='\n'.join(
                t for t in (
                    informe.seccion_academica.strip(),
                    '<p><b>Asesorías y tutorías</b></p>' if asesorias else '',
                    asesorias,
                ) if t
            ),
            seccion_extension_interaccion='',
            seccion_asesorias_tutorias='',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0121_fondo_fuera_de_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefondo',
            name='seccion_extension_universitaria',
            field=models.TextField(blank=True, default='', help_text='Cursos, seminarios, talleres, conferencias, asistencia técnica, voluntariado.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='seccion_gestion',
            field=models.TextField(blank=True, default='', help_text='Convenios, reuniones, coordinación, modalidades de graduación, políticas académicas.'),
        ),
        migrations.AddField(
            model_name='informefondo',
            name='seccion_interaccion_social',
            field=models.TextField(blank=True, default='', help_text='Programas y proyectos de proyección social, ferias, campañas, consultorías.'),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='seccion_asesorias_tutorias',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='informefondo',
            name='seccion_extension_interaccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(pasar_editables_a_secciones_del_reglamento, migrations.RunPython.noop),
    ]
