# Generated by Django 5.2.7 on 2026-10-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0122_informe_secciones_reglamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaldoVacacionesGestion',
        ),
    ]
