# Generated by Django 5.2.7 on 2026-04-07 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fondos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('responsable', models.CharField(max_length=500)),
                ('productos_esperados', models.TextField()),
                ('mes_inicio', models.CharField(max_length=20)),
                ('mes_fin', models.CharField(max_length=20)),
                ('indicador_descripcion', models.TextField(blank=True, null=True)),
                ('indicador_unidad', models.CharField(choices=[('numero', 'Número'), ('porcentaje', 'Porcentaje')], default='numero', max_length=50)),
                ('indicador_linea_base', models.IntegerField()),
                ('indicador_meta', models.IntegerField()),
                ('monto_funcion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_inversion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('ejecutado', 'Ejecutado'), ('suspendido', 'Suspendido')], default='programado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField(verbose_name='Año de Gestión')),
                ('unidad_solicitante', models.CharField(max_length=200)),
                ('programa', models.CharField(max_length=200)),
                ('objetivo_gestion_institucional', models.TextField()),
                ('fecha_elaboracion', models.DateField()),
                ('estado', models.CharField(choices=[('elaboracion', 'En elaboración'), ('revision', 'En revisión'), ('observado', 'Observado'), ('aprobado', 'Aprobado'), ('ejecucion', 'En ejecución')], default='elaboracion', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('ciclo_revision_actual', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('funcion', 'Funcionamiento'), ('funcionamiento', 'Funcionamiento'), ('inversion', 'Inversión')], db_index=True, default='funcion', max_length=20)),
                ('partida', models.CharField(db_index=True, max_length=50)),
                ('item', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('caracteristicas', models.TextField(blank=True)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes_requerimiento', models.CharField(max_length=50)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_presupuesto', to='poa_document.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField(db_index=True, verbose_name='Año de Gestión')),
                ('abierto', models.BooleanField(default=True, verbose_name='Hilo activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='poa_document.documentopoa', verbose_name='Documento POA')),
            ],
            options={
                'verbose_name': 'Conversación POA',
                'verbose_name_plural': 'Conversaciones POA',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumentoPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Creacion'), ('edicion', 'Edicion'), ('envio_revision', 'Envio a revision'), ('aprobacion_revision', 'Aprobacion de revision'), ('observacion_revision', 'Observacion de revision'), ('aprobacion_final', 'Aprobacion final')], max_length=30)),
                ('descripcion', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('datos_evento', models.JSONField(blank=True, default=dict)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='poa_document.documentopoa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_documentos_poa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Documento POA',
                'verbose_name_plural': 'Historiales de Documento POA',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MensajeComentarioPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Mensaje')),
                ('es_revisor', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_poa', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='poa_document.comentariopoa', verbose_name='Hilo de conversación')),
            ],
            options={
                'verbose_name': 'Mensaje POA',
                'verbose_name_plural': 'Mensajes POA',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='poa_document.documentopoa')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='poa_document.objetivoespecifico'),
        ),
        migrations.CreateModel(
            name='UsuarioPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('elaborador', 'Elaborador del POA'), ('director_carrera', 'Director de Carrera'), ('revisor_1', 'Entidad Revisora 1'), ('revisor_2', 'Entidad Revisora 2'), ('revisor_3', 'Entidad Revisora 3'), ('revisor_4', 'Entidad Revisora 4')], max_length=30, verbose_name='Rol POA')),
                ('nombre_entidad', models.CharField(blank=True, help_text='Para roles de revisor: nombre de la entidad revisora (ej. DAF, VRA)', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_poa_docente', to='fondos.docente', verbose_name='Docente vinculado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos_poa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Usuario POA',
                'verbose_name_plural': 'Usuarios POA',
                'ordering': ['rol', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RevisionDocumentoPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_revision', models.PositiveIntegerField(default=1)),
                ('tipo_revisor', models.CharField(choices=[('entidad', 'Entidad Revisora'), ('director', 'Director de Carrera')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('observado', 'Observado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='poa_document.documentopoa')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_revision_poa', to=settings.AUTH_USER_MODEL)),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_documento_poa', to='poa_document.usuariopoa')),
            ],
            options={
                'verbose_name': 'Revision de Documento POA',
                'verbose_name_plural': 'Revisiones de Documento POA',
                'ordering': ['tipo_revisor', 'fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='documentopoa',
            name='elaborado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_elaborados', to='poa_document.usuariopoa'),
        ),
        migrations.AddField(
            model_name='documentopoa',
            name='jefe_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_jefe', to='poa_document.usuariopoa'),
        ),
        migrations.AddConstraint(
            model_name='usuariopoa',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'rol'), name='unique_user_rol_poa'),
        ),
        migrations.AddConstraint(
            model_name='revisiondocumentopoa',
            constraint=models.UniqueConstraint(fields=('documento', 'ciclo_revision', 'revisor'), name='unique_revision_documento_poa_por_ciclo'),
        ),
        migrations.AlterUniqueTogether(
            name='documentopoa',
            unique_together={('gestion', 'unidad_solicitante', 'programa')},
        ),
    ]
