# Generated by Django 5.2.6 on 2026-03-11 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0028_docente_fecha_ingreso'),
        ('poa_document', '0001_initial'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
