# Generated by Django 5.2.6 on 2026-03-11 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0002_add_usuario_poa'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
