# Generated by Django 5.2.6 on 2026-03-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0003_remove_persona_use_usuario_poa'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
