# Generated by Django 4.2.16 on 2026-03-12 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fondos', '0028_docente_fecha_ingreso'),
        ('poa_document', '0004_add_estado_documentopoa'),
    ]

    operations = [
        # No-op: 0001_initial already handles this.
    ]
