# Generated by Django 5.2.7 on 2026-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0008_add_comentario_poa'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentopoa',
            index=models.Index(fields=['gestion', 'unidad_solicitante'], name='poa_doc_gestion_unidad_idx'),
        ),
    ]
