# Generated by Django 6.0.4 on 2026-04-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0010_alter_documentopoa_unidad_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopoa',
            name='elaborado_por',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentopoa',
            name='jefe_unidad',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuariopoa',
            name='nombre_entidad',
            field=models.CharField(blank=True, help_text='No se utiliza en la configuración actual del módulo POA.', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuariopoa',
            name='rol',
            field=models.CharField(choices=[('elaborador', 'Elaborador del POA')], max_length=30, verbose_name='Rol POA'),
        ),
    ]
