# Generated by Django 6.0.4 on 2026-04-24 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0011_alter_documentopoa_elaborado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariopoa',
            name='usuario_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_poa_usuario_dos', to=settings.AUTH_USER_MODEL, verbose_name='Segundo usuario (revisor)'),
        ),
        migrations.AddField(
            model_name='comentariopoa',
            name='usuario_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_poa_usuario_uno', to=settings.AUTH_USER_MODEL, verbose_name='Primer usuario (elaborador)'),
        ),
        migrations.AddField(
            model_name='mensajecomentariopoa',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_poa_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario (quien recibe)'),
        ),
        migrations.AlterField(
            model_name='mensajecomentariopoa',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_poa_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Autor (quien envía)'),
        ),
        migrations.AddIndex(
            model_name='comentariopoa',
            index=models.Index(fields=['usuario_uno', 'usuario_dos', 'gestion'], name='poa_documen_usuario_66d847_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajecomentariopoa',
            index=models.Index(fields=['autor', 'destinatario', 'fecha'], name='poa_documen_autor_i_75aaae_idx'),
        ),
    ]
