# Generated by Django 6.0.4 on 2026-04-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0012_comentariopoa_usuario_dos_comentariopoa_usuario_uno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopoa',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='poa_document.documentopoa', verbose_name='Documento POA'),
        ),
    ]
