# Generated by Django 6.0.4 on 2026-04-24 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0013_alter_comentariopoa_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_chat_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_chat_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'db_table': 'mensajes_chat',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['emisor', 'receptor', 'fecha'], name='mensajes_ch_emisor__aa6e22_idx'), models.Index(fields=['receptor', 'emisor', 'fecha'], name='mensajes_ch_recepto_e8a442_idx')],
            },
        ),
    ]
