# Generated by Django 6.0.4 on 2026-04-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0014_mensajechat'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comentariopoa',
            name='poa_documen_usuario_66d847_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensajecomentariopoa',
            name='poa_documen_autor_i_75aaae_idx',
        ),
        migrations.RemoveField(
            model_name='mensajecomentariopoa',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='mensajecomentariopoa',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='mensajecomentariopoa',
            name='destinatario',
        ),
        migrations.DeleteModel(
            name='ComentarioPOA',
        ),
        migrations.DeleteModel(
            name='MensajeComentarioPOA',
        ),
    ]
