# Generated by Django 6.0.4 on 2026-04-24 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0015_remove_comentariopoa_poa_documen_usuario_66d847_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_chat_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario bloqueado')),
                ('bloqueador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_chat_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que bloquea')),
            ],
            options={
                'verbose_name': 'Bloqueo de chat',
                'verbose_name_plural': 'Bloqueos de chat',
                'db_table': 'bloqueos_chat',
                'unique_together': {('bloqueador', 'bloqueado')},
            },
        ),
        migrations.AddIndex(
            model_name='bloqueochat',
            index=models.Index(fields=['bloqueador', 'bloqueado'], name='bloqueos_ch_bloquea_1c7bf7_idx'),
        ),
    ]
