# Generated by Django 6.0.4 on 2026-05-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0016_bloqueochat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados_logrados', models.TextField(blank=True, default='', verbose_name='Resultados logrados')),
                ('programado', models.IntegerField(default=0, verbose_name='Programado')),
                ('ejecutado', models.IntegerField(default=0, verbose_name='Ejecutado')),
                ('grado_cumplimiento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Grado de cumplimiento (%)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evidencia de actividad',
                'verbose_name_plural': 'Evidencias de actividad',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('link', 'Link')], default='imagen', max_length=16)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/%Y/%m')),
                ('url', models.URLField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo de evidencia',
                'verbose_name_plural': 'Archivos de evidencia',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.RenameIndex(
            model_name='bloqueochat',
            new_name='bloqueos_ch_bloquea_7c58cd_idx',
            old_name='bloqueos_ch_bloquea_1c7bf7_idx',
        ),
        migrations.AddField(
            model_name='evidencia',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='poa_document.actividad', verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='evidenciaarchivo',
            name='evidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='poa_document.evidencia'),
        ),
    ]
