# Generated by Django 5.2.7 on 2026-05-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0017_evidencia_evidenciaarchivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_ejecucion', 'En ejecución'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('en_proceso', 'En Proceso'), ('ejecutado', 'Ejecutado'), ('suspendido', 'Suspendido')], default='programado', max_length=20),
        ),
    ]
