# Generated by Django 5.2.7 on 2026-07-24 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def poblar_carrera_accesos_poa(apps, schema_editor):
    UsuarioPOA = apps.get_model('poa_document', 'UsuarioPOA')
    PerfilUsuario = apps.get_model('fondos', 'PerfilUsuario')
    AsignacionCarrera = apps.get_model('fondos', 'AsignacionCarrera')
    db_alias = schema_editor.connection.alias

    for acceso in UsuarioPOA.objects.using(db_alias).all():
        carrera_id = None
        if acceso.user_id:
            perfil = PerfilUsuario.objects.using(db_alias).filter(user_id=acceso.user_id).first()
            carrera_id = getattr(perfil, 'carrera_id', None)
            if not carrera_id:
                asignacion = AsignacionCarrera.objects.using(db_alias).filter(
                    user_id=acceso.user_id,
                    activo=True,
                    carrera_id__isnull=False,
                ).order_by('id').first()
                carrera_id = getattr(asignacion, 'carrera_id', None)

        if not carrera_id and acceso.docente_id:
            asignacion = AsignacionCarrera.objects.using(db_alias).filter(
                docente_id=acceso.docente_id,
                activo=True,
                carrera_id__isnull=False,
            ).order_by('id').first()
            carrera_id = getattr(asignacion, 'carrera_id', None)

        if carrera_id:
            UsuarioPOA.objects.using(db_alias).filter(pk=acceso.pk).update(carrera_id=carrera_id)

    carrera_ids = UsuarioPOA.objects.using(db_alias).filter(
        rol='elaborador',
        activo=True,
        carrera_id__isnull=False,
    ).values_list('carrera_id', flat=True).distinct()

    for carrera_id in carrera_ids:
        activos = list(UsuarioPOA.objects.using(db_alias).filter(
            rol='elaborador',
            activo=True,
            carrera_id=carrera_id,
        ).order_by('id').values_list('id', flat=True))
        if len(activos) <= 1:
            continue
        UsuarioPOA.objects.using(db_alias).filter(id__in=activos[1:]).update(activo=False)


def revertir_poblar_carrera_accesos_poa(apps, schema_editor):
    UsuarioPOA = apps.get_model('poa_document', 'UsuarioPOA')
    UsuarioPOA.objects.using(schema_editor.connection.alias).update(carrera_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0063_remove_docentecarrera_resolucion_nombramiento'),
        ('poa_document', '0018_alter_actividad_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionDocumentoPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_revision', models.PositiveIntegerField(default=1)),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Observacion de Documento POA',
                'verbose_name_plural': 'Observaciones de Documento POA',
                'ordering': ['ciclo_revision', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambioPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(choices=[('documento', 'Documento'), ('objetivo', 'Objetivo especifico'), ('actividad', 'Actividad'), ('presupuesto', 'Presupuesto')], max_length=20)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio POA',
                'verbose_name_plural': 'Solicitudes de Cambio POA',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='usuariopoa',
            name='unique_user_rol_poa',
        ),
        migrations.AddField(
            model_name='usuariopoa',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Carrera a la que pertenece este acceso POA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_poa', to='fondos.carrera', verbose_name='Carrera'),
        ),
        migrations.RunPython(poblar_carrera_accesos_poa, revertir_poblar_carrera_accesos_poa),
        migrations.AlterField(
            model_name='historialdocumentopoa',
            name='tipo_evento',
            field=models.CharField(choices=[('creacion', 'Creacion'), ('edicion', 'Edicion'), ('envio_revision', 'Envio a revision'), ('aprobacion_revision', 'Aprobacion de revision'), ('observacion_revision', 'Observacion de revision'), ('aprobacion_final', 'Aprobacion final'), ('inicio_ejecucion', 'Inicio de ejecucion'), ('solicitud_cambio', 'Solicitud de cambio'), ('aprobacion_cambio', 'Aprobacion de cambio'), ('rechazo_cambio', 'Rechazo de cambio'), ('evidencia', 'Evidencia')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='usuariopoa',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'rol', 'carrera'), name='unique_user_rol_carrera_poa'),
        ),
        migrations.AddConstraint(
            model_name='usuariopoa',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('carrera__isnull', False), ('rol', 'elaborador')), fields=('carrera', 'rol'), name='unique_active_elaborador_poa_por_carrera'),
        ),
        migrations.AddField(
            model_name='observaciondocumentopoa',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_poa_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observaciondocumentopoa',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_checklist', to='poa_document.documentopoa'),
        ),
        migrations.AddField(
            model_name='observaciondocumentopoa',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_poa_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcambiopoa',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='poa_document.documentopoa'),
        ),
        migrations.AddField(
            model_name='solicitudcambiopoa',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cambio_poa_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcambiopoa',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cambio_poa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='observaciondocumentopoa',
            index=models.Index(fields=['documento', 'ciclo_revision'], name='poa_documen_documen_f63728_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcambiopoa',
            index=models.Index(fields=['documento', 'estado'], name='poa_documen_documen_f24824_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcambiopoa',
            index=models.Index(fields=['tipo_objeto', 'objeto_id'], name='poa_documen_tipo_ob_8745f8_idx'),
        ),
    ]
