# Generated by Django 5.2.7 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0063_remove_docentecarrera_resolucion_nombramiento'),
        ('poa_document', '0019_observaciondocumentopoa_solicitudcambiopoa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del programa')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_poa', to='fondos.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Programa POA',
                'verbose_name_plural': 'Programas POA',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='programapoa',
            constraint=models.UniqueConstraint(fields=('carrera', 'nombre'), name='unique_programa_poa_por_carrera'),
        ),
        migrations.AddIndex(
            model_name='programapoa',
            index=models.Index(fields=['carrera', 'activo'], name='poa_prog_carr_act_idx'),
        ),
    ]
