# Generated by Django 5.2.7 on 2026-08-26 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0071_mensajeobservacion_responde_a'),
        ('poa_document', '0023_rename_seguimiento_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenCompraPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('caracteristicas', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(max_length=20)),
                ('cantidad_planificada', models.PositiveIntegerField()),
                ('cantidad_comprada', models.PositiveIntegerField()),
                ('costo_unitario_real', models.DecimalField(decimal_places=2, max_digits=12)),
                ('origen_detalles', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRecepcionMaterialPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.PositiveIntegerField()),
                ('costo_unitario_real', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_detalle', to='poa_document.detalleordencomprapoa')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaMaterialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('nombre_receptor', models.CharField(max_length=255)),
                ('ci_receptor', models.CharField(blank=True, default='', max_length=50)),
                ('cargo_receptor', models.CharField(blank=True, default='', max_length=255)),
                ('telefono_receptor', models.CharField(blank=True, default='', max_length=50)),
                ('acta_archivo', models.FileField(blank=True, null=True, upload_to='poa/entregas/%Y/%m')),
                ('observacion', models.TextField(blank=True, default='')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('anulada', models.BooleanField(default=False)),
                ('motivo_anulacion', models.TextField(blank=True, default='')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_material', to='poa_document.actividad')),
                ('detalle_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='poa_document.detallerecepcionmaterialpoa')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_material_poa_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.PositiveIntegerField()),
                ('numero', models.CharField(max_length=80)),
                ('proveedor', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('recibiendo', 'Recibiendo'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='emitida', max_length=20)),
                ('respaldo', models.FileField(blank=True, null=True, upload_to='poa/compras/%Y/%m')),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo_anulacion', models.TextField(blank=True, default='')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_poa_anuladas', to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_poa', to='fondos.carrera')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_poa_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='detalleordencomprapoa',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='poa_document.ordencomprapoa'),
        ),
        migrations.CreateModel(
            name='RecepcionMaterialPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_respaldo', models.CharField(blank=True, default='', max_length=100)),
                ('recibido_por', models.CharField(max_length=255)),
                ('respaldo', models.FileField(blank=True, null=True, upload_to='poa/recepciones/%Y/%m')),
                ('observacion', models.TextField(blank=True, default='')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('anulada', models.BooleanField(default=False)),
                ('motivo_anulacion', models.TextField(blank=True, default='')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='poa_document.ordencomprapoa')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_poa_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='detallerecepcionmaterialpoa',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='poa_document.recepcionmaterialpoa'),
        ),
        migrations.AddConstraint(
            model_name='ordencomprapoa',
            constraint=models.UniqueConstraint(fields=('carrera', 'gestion', 'numero'), name='poa_orden_numero_carrera_gestion'),
        ),
    ]
