# Generated by Django 5.2.7 on 2026-09-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa_document', '0026_catalogos_internos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaarchivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='poa/evidencias/%Y/%m'),
        ),
    ]
