# Generated by Django 5.2.7 on 2026-09-26 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0091_carrera_relaciones_protect'),
        ('poa_document', '0027_alter_evidenciaarchivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopoa',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Carrera a la que pertenece este acceso POA.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesos_poa', to='fondos.carrera', verbose_name='Carrera'),
        ),
    ]
